package com.app.controller;

import java.security.Principal;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.Authentication;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.app.entity.User;
import com.app.payload.UserRequest;
import com.app.payload.UserResponse;
import com.app.security.jwt.JwtUtil;
import com.app.service.IUserService;

@RestController
@RequestMapping("/user")
public class UserRestController {

	@Autowired
	private AuthenticationManager authenticationManager;
	
	@Autowired
	private IUserService userService;
	
	@Autowired
	private JwtUtil jwtUtil;
	
	@PostMapping("/save")
	public ResponseEntity<String> saveUser(@RequestBody User user){
		userService.saveUser(user);
		return ResponseEntity.ok("User Created");
	}
	
	@PostMapping("/login")
	public ResponseEntity<UserResponse> loginUser(@RequestBody UserRequest userRequest) {
		
		Authentication authenticate = authenticationManager.authenticate(new UsernamePasswordAuthenticationToken(userRequest.getUsername(), 
				userRequest.getPassword()));
		
		String token = jwtUtil.genrateToken(userRequest.getUsername());
		return ResponseEntity.ok(new UserResponse(token, "Generated By Mr. Rahul Kumar"));
	}
	
	@GetMapping("/welcome")
	public ResponseEntity<String> showUserData(Principal p){
		return ResponseEntity.ok("Hello : " + p.getName());
	}
	
}
